# Generated by Django 5.2.13 on 2026-09-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_compra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
